/* ========================================================================
 * Copyright 2014 macrosoft
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 macrosoft

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.qualifier

*/

package co.edu.uniandes.csw.macrosoft.user.logic.ejb;
import java.util.List;
import javax.inject.Inject;

import co.edu.uniandes.csw.macrosoft.user.logic.dto.UserDTO;
import co.edu.uniandes.csw.macrosoft.user.logic.dto.UserPageDTO;
import co.edu.uniandes.csw.macrosoft.user.logic.api._IUserLogicService;
import co.edu.uniandes.csw.macrosoft.user.persistence.api.IUserPersistence;

public abstract class _UserLogicService implements _IUserLogicService {

	@Inject
	protected IUserPersistence persistance;

	public UserDTO createUser(UserDTO user){
		return persistance.createUser( user); 
    }

	public List<UserDTO> getUsers(){
		return persistance.getUsers(); 
	}

	public UserPageDTO getUsers(Integer page, Integer maxRecords){
		return persistance.getUsers(page, maxRecords); 
	}

	public UserDTO getUser(Long id){
		return persistance.getUser(id); 
	}

	public void deleteUser(Long id){
	    persistance.deleteUser(id); 
	}

	public void updateUser(UserDTO user){
	    persistance.updateUser(user); 
	}	
}